"""add_comprehensive_student_tracking_tables

Revision ID: 4f74cb7aa29a
Revises: 6b8c677c9c4f
Create Date: 2025-06-19 16:34:48.298748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f74cb7aa29a'
down_revision = '6b8c677c9c4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentlearningprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('learning_style', sa.String(), nullable=True),
    sa.Column('learning_style_confidence', sa.Float(), nullable=False),
    sa.Column('preferred_time_of_day', sa.String(), nullable=True),
    sa.Column('average_session_duration_minutes', sa.Float(), nullable=False),
    sa.Column('optimal_session_length_minutes', sa.Integer(), nullable=True),
    sa.Column('average_response_time_ms', sa.Float(), nullable=False),
    sa.Column('preferred_help_method', sa.String(), nullable=True),
    sa.Column('collaboration_preference', sa.String(), nullable=True),
    sa.Column('common_struggle_areas', sa.JSON(), nullable=True),
    sa.Column('struggle_recovery_methods', sa.JSON(), nullable=True),
    sa.Column('resilience_score', sa.Float(), nullable=False),
    sa.Column('motivation_drivers', sa.JSON(), nullable=True),
    sa.Column('engagement_triggers', sa.JSON(), nullable=True),
    sa.Column('overall_success_rate', sa.Float(), nullable=False),
    sa.Column('average_completion_time_ratio', sa.Float(), nullable=False),
    sa.Column('consistency_score', sa.Float(), nullable=False),
    sa.Column('ai_generated_insights', sa.JSON(), nullable=True),
    sa.Column('personalized_recommendations', sa.JSON(), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('total_study_time_hours', sa.Float(), nullable=False),
    sa.Column('last_activity_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('studentsessiontracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.Column('current_node_id', sa.String(), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('nodes_completed', sa.JSON(), nullable=True),
    sa.Column('nodes_attempted', sa.JSON(), nullable=True),
    sa.Column('total_interactions', sa.Integer(), nullable=False),
    sa.Column('active_time_seconds', sa.Integer(), nullable=False),
    sa.Column('idle_time_seconds', sa.Integer(), nullable=False),
    sa.Column('total_chat_messages', sa.Integer(), nullable=False),
    sa.Column('total_code_changes', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('average_response_time_ms', sa.Float(), nullable=False),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('help_requests', sa.Integer(), nullable=False),
    sa.Column('current_struggle_score', sa.Float(), nullable=False),
    sa.Column('struggle_alerts_triggered', sa.Integer(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('learning_style_indicators', sa.JSON(), nullable=True),
    sa.Column('engagement_patterns', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatinteraction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_tracking_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('message_type', sa.Enum('STUDENT_QUESTION', 'AI_RESPONSE', 'HINT_REQUEST', 'CODE_QUESTION', 'CLARIFICATION', 'ENCOURAGEMENT', name='messagetype'), nullable=False),
    sa.Column('content', sa.String(length=5000), nullable=False),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('emotional_tone', sa.String(), nullable=True),
    sa.Column('intent_classification', sa.String(), nullable=True),
    sa.Column('complexity_score', sa.Float(), nullable=True),
    sa.Column('ai_confidence_score', sa.Float(), nullable=True),
    sa.Column('requires_human_intervention', sa.Boolean(), nullable=False),
    sa.Column('additional_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['session_tracking_id'], ['studentsessiontracking.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('codeinteraction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_tracking_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('interaction_type', sa.String(), nullable=False),
    sa.Column('code_snapshot', sa.String(length=10000), nullable=False),
    sa.Column('code_diff', sa.String(length=2000), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('characters_added', sa.Integer(), nullable=False),
    sa.Column('characters_deleted', sa.Integer(), nullable=False),
    sa.Column('lines_of_code', sa.Integer(), nullable=False),
    sa.Column('syntax_errors', sa.JSON(), nullable=True),
    sa.Column('execution_result', sa.String(length=2000), nullable=True),
    sa.Column('execution_success', sa.Boolean(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('is_significant_change', sa.Boolean(), nullable=False),
    sa.Column('completion_progress', sa.Float(), nullable=False),
    sa.Column('additional_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['session_tracking_id'], ['studentsessiontracking.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('codesubmission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_tracking_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('submission_number', sa.Integer(), nullable=False),
    sa.Column('submitted_code', sa.String(length=10000), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('test_results', sa.JSON(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('memory_usage_mb', sa.Float(), nullable=True),
    sa.Column('compilation_errors', sa.JSON(), nullable=True),
    sa.Column('runtime_errors', sa.JSON(), nullable=True),
    sa.Column('logic_errors', sa.JSON(), nullable=True),
    sa.Column('ai_feedback', sa.String(length=2000), nullable=True),
    sa.Column('suggested_improvements', sa.JSON(), nullable=True),
    sa.Column('time_since_start_seconds', sa.Integer(), nullable=False),
    sa.Column('time_since_last_attempt_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['session_tracking_id'], ['studentsessiontracking.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('struggleanalysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_tracking_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('struggle_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='struggleseverity'), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=True),
    sa.Column('ai_analysis', sa.String(length=1000), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('intervention_suggested', sa.Boolean(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_time_seconds', sa.Integer(), nullable=True),
    sa.Column('resolution_method', sa.String(), nullable=True),
    sa.Column('instructor_notified', sa.Boolean(), nullable=False),
    sa.Column('instructor_response_time_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['session_tracking_id'], ['studentsessiontracking.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('struggleanalysis')
    op.drop_table('codesubmission')
    op.drop_table('codeinteraction')
    op.drop_table('chatinteraction')
    op.drop_table('studentsessiontracking')
    op.drop_table('studentlearningprofile')
    # ### end Alembic commands ### 