"""Add audio/TTS preferences to learning sessions

Revision ID: 5f3218fd589d
Revises: bba7062c42b0
Create Date: 2025-06-09 16:01:24.381586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f3218fd589d'
down_revision: Union[str, None] = 'bba7062c42b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_sessions', sa.Column('audio_enabled', sa.Boolean(), nullable=True))
    op.add_column('learning_sessions', sa.Column('preferred_voice', sa.String(length=50), nullable=True))
    op.add_column('learning_sessions', sa.Column('speech_rate', sa.Float(), nullable=True))
    op.add_column('learning_sessions', sa.Column('audio_format', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_sessions', 'audio_format')
    op.drop_column('learning_sessions', 'speech_rate')
    op.drop_column('learning_sessions', 'preferred_voice')
    op.drop_column('learning_sessions', 'audio_enabled')
    # ### end Alembic commands ###
