"""Add start_time and end_time to sessions

Revision ID: 6b8c677c9c4f
Revises: 8339f09cdb03
Create Date: 2025-06-19 13:35:52.423845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b8c677c9c4f'
down_revision = '8339f09cdb03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('session', sa.Column('end_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'end_time')
    op.drop_column('session', 'start_time')
    # ### end Alembic commands ### 