"""Add learning graph models - fixed import

Revision ID: bba7062c42b0
Revises: 545aefc087ac
Create Date: 2025-06-09 15:31:14.197839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bba7062c42b0'
down_revision: Union[str, None] = '545aefc087ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('learning_objectives', sa.JSON(), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('estimated_time_minutes', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('explanation_text', sa.Text(), nullable=True),
    sa.Column('code_examples', sa.JSON(), nullable=True),
    sa.Column('visual_aids', sa.JSON(), nullable=True),
    sa.Column('practice_exercises', sa.JSON(), nullable=True),
    sa.Column('assessment_questions', sa.JSON(), nullable=True),
    sa.Column('mastery_threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_concepts_category'), 'learning_concepts', ['category'], unique=False)
    op.create_index(op.f('ix_learning_concepts_id'), 'learning_concepts', ['id'], unique=False)
    op.create_index(op.f('ix_learning_concepts_name'), 'learning_concepts', ['name'], unique=True)
    op.create_index(op.f('ix_learning_concepts_slug'), 'learning_concepts', ['slug'], unique=True)
    op.create_table('learning_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal', sa.String(length=500), nullable=True),
    sa.Column('concept_sequence', sa.JSON(), nullable=True),
    sa.Column('current_position', sa.Integer(), nullable=True),
    sa.Column('difficulty_preference', sa.Float(), nullable=True),
    sa.Column('pacing_preference', sa.String(length=20), nullable=True),
    sa.Column('learning_style', sa.JSON(), nullable=True),
    sa.Column('completion_percentage', sa.Float(), nullable=True),
    sa.Column('estimated_completion_hours', sa.Float(), nullable=True),
    sa.Column('actual_time_spent_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_paths_id'), 'learning_paths', ['id'], unique=False)
    op.create_index(op.f('ix_learning_paths_session_id'), 'learning_paths', ['session_id'], unique=False)
    op.create_index(op.f('ix_learning_paths_user_id'), 'learning_paths', ['user_id'], unique=False)
    op.create_table('assessment_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('questions_asked', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_possible_score', sa.Float(), nullable=True),
    sa.Column('assessment_type', sa.String(length=50), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['learning_concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_results_id'), 'assessment_results', ['id'], unique=False)
    op.create_index(op.f('ix_assessment_results_session_id'), 'assessment_results', ['session_id'], unique=False)
    op.create_index(op.f('ix_assessment_results_user_id'), 'assessment_results', ['user_id'], unique=False)
    op.create_table('concept_prerequisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_type', sa.String(length=20), nullable=True),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['learning_concepts.id'], ),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['learning_concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_prerequisites_id'), 'concept_prerequisites', ['id'], unique=False)
    op.create_table('student_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('time_spent_minutes', sa.Integer(), nullable=True),
    sa.Column('attempts_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('first_introduced_at', sa.DateTime(), nullable=True),
    sa.Column('last_practiced_at', sa.DateTime(), nullable=True),
    sa.Column('mastered_at', sa.DateTime(), nullable=True),
    sa.Column('learning_velocity', sa.Float(), nullable=True),
    sa.Column('struggle_indicators', sa.JSON(), nullable=True),
    sa.Column('preferred_explanations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['learning_concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_progress_id'), 'student_progress', ['id'], unique=False)
    op.create_index(op.f('ix_student_progress_session_id'), 'student_progress', ['session_id'], unique=False)
    op.create_index(op.f('ix_student_progress_user_id'), 'student_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_progress_user_id'), table_name='student_progress')
    op.drop_index(op.f('ix_student_progress_session_id'), table_name='student_progress')
    op.drop_index(op.f('ix_student_progress_id'), table_name='student_progress')
    op.drop_table('student_progress')
    op.drop_index(op.f('ix_concept_prerequisites_id'), table_name='concept_prerequisites')
    op.drop_table('concept_prerequisites')
    op.drop_index(op.f('ix_assessment_results_user_id'), table_name='assessment_results')
    op.drop_index(op.f('ix_assessment_results_session_id'), table_name='assessment_results')
    op.drop_index(op.f('ix_assessment_results_id'), table_name='assessment_results')
    op.drop_table('assessment_results')
    op.drop_index(op.f('ix_learning_paths_user_id'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_session_id'), table_name='learning_paths')
    op.drop_index(op.f('ix_learning_paths_id'), table_name='learning_paths')
    op.drop_table('learning_paths')
    op.drop_index(op.f('ix_learning_concepts_slug'), table_name='learning_concepts')
    op.drop_index(op.f('ix_learning_concepts_name'), table_name='learning_concepts')
    op.drop_index(op.f('ix_learning_concepts_id'), table_name='learning_concepts')
    op.drop_index(op.f('ix_learning_concepts_category'), table_name='learning_concepts')
    op.drop_table('learning_concepts')
    # ### end Alembic commands ###
