"""Initial migration

Revision ID: f4df727ef4a9
Revises: 
Create Date: 2025-06-09 09:55:52.176334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4df727ef4a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=True),
    sa.Column('user_input', sa.Text(), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('audio_duration', sa.Float(), nullable=True),
    sa.Column('response_latency', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_logs_id'), 'conversation_logs', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_logs_node_id'), 'conversation_logs', ['node_id'], unique=False)
    op.create_index(op.f('ix_conversation_logs_session_id'), 'conversation_logs', ['session_id'], unique=False)
    op.create_table('learning_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_metrics_id'), 'learning_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_learning_metrics_node_id'), 'learning_metrics', ['node_id'], unique=False)
    op.create_index(op.f('ix_learning_metrics_session_id'), 'learning_metrics', ['session_id'], unique=False)
    op.create_table('learning_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('lesson_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_sessions_id'), 'learning_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_learning_sessions_lesson_id'), 'learning_sessions', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_learning_sessions_session_id'), 'learning_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_learning_sessions_user_id'), 'learning_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_sessions_user_id'), table_name='learning_sessions')
    op.drop_index(op.f('ix_learning_sessions_session_id'), table_name='learning_sessions')
    op.drop_index(op.f('ix_learning_sessions_lesson_id'), table_name='learning_sessions')
    op.drop_index(op.f('ix_learning_sessions_id'), table_name='learning_sessions')
    op.drop_table('learning_sessions')
    op.drop_index(op.f('ix_learning_metrics_session_id'), table_name='learning_metrics')
    op.drop_index(op.f('ix_learning_metrics_node_id'), table_name='learning_metrics')
    op.drop_index(op.f('ix_learning_metrics_id'), table_name='learning_metrics')
    op.drop_table('learning_metrics')
    op.drop_index(op.f('ix_conversation_logs_session_id'), table_name='conversation_logs')
    op.drop_index(op.f('ix_conversation_logs_node_id'), table_name='conversation_logs')
    op.drop_index(op.f('ix_conversation_logs_id'), table_name='conversation_logs')
    op.drop_table('conversation_logs')
    # ### end Alembic commands ###
